promptToReturnFromSubprocess: false
keybinding:
  universal:
    createPatchOptionsMenu: <c-k>
  files:
    commitChangesWithEditor: <disabled>
  commits:
    renameCommitWithEditor: <disabled>
customCommands:
  - key: 'C'
    context: 'global'
    command: 'run-in-pane "git commit"'
  - key: 'O'
    context: 'global'
    command: 'charm .'
  - key: 'R'
    context: 'commits'
    command: 'run-in-pane "git reword {{.SelectedLocalCommit.Sha}}"'
  - key: "G"
    command: "gh pr view -w {{.SelectedLocalBranch.Name}}"
    context: "localBranches"
    output: log
  - key: "c"
    command: "git push --set-upstream origin {{.SelectedLocalBranch.Name}} && gh c"
    context: "localBranches"
    output: log
